### ISSUE TITLE
Don't work setWidth() for MenuStyle

### ISSUE THREAD

**Issue by zhdanov** [php-school/cli-menu#263]
Hello,

```php
$style = (new MenuStyle())->setWidth(200)->setBg('black')->setFg('white');
```

Colors works. Width not works.

**Comment by mikeymike** [comment]
Hey @zhdanov, thanks for the report. 

Could you supply an example that shows how you're using this? 

We have some code examples in the src, `examples/basic-centered.php` is one which alters the width which I've played with to also alter colour etc like above but I couldn't recreate a scenario which didn't alter the width. 

Thanks!

**Comment by zhdanov** [comment]
Hey @mikeymike , sure:

```php
<?php
require __DIR__.'/vendor/autoload.php';

use PhpSchool\CliMenu\Builder\CliMenuBuilder;
use PhpSchool\CliMenu\CliMenu;
use PhpSchool\CliMenu\MenuStyle;
use PhpSchool\CliMenu\Action\GoBackAction;

$builder = new CliMenuBuilder;

$itemCallable = function ($menu) {
    $style = (new MenuStyle())->setWidth(200)->setBg('black')->setFg('white');

    $result = $menu->askText($style)
        ->setPromptText('Title')
        ->setPlaceholderText('Placeholder')
        ->ask();
};  

$builder->addSubMenu('Item 1', function (CliMenuBuilder $b) use ($itemCallable) {
    $b->setTitle('Menu > Item 1');
    
    $b->addItem('Sub item', function (CliMenu $menu) use ($itemCallable) {
        $itemCallable($menu);
    }); 
});

$menu = $builder->build();

$menu->open();
```

**Comment by mikeymike** [comment]
Hey @zhdanov I've had a quick look over this and you're totally right the dialogues don't currently utilise the width set by the style. Instead, these are calculated dynamically based on the parents width, the dialogues content and the dialogue padding styles. 

Using `setPaddingLeftRight` instead of `setWidth` may be a suitable solution to your problem. I'm going to keep this issue open though as we may want to use width if it's been specifically set and then fallback to dynamic if it's not set. 

Thanks again for the report!

**Comment by zhdanov** [comment]
Hey @mikeymike thanks! setPaddingLeftRight() works fine!
